CREATE PROCEDURE Add_customer
@USERNAME varchar(20),
@PASSWORD varchar(8),
@CUST_NAME varchar(20),
@CUST_ADDRESS varchar(100),
@PHONE decimal(10,0)
	
AS
	INSERT INTO CUSTOMER(USERNAME,PASSWORD,CUST_NAME,CUST_ADDRESS,PHONE) VALUES(@USERNAME,@PASSWORD,@CUST_NAME,@CUST_ADDRESS,@PHONE)
RETURN 0
 