CREATE TABLE [dbo].[DELIVERY] (
    [STAFF_ID] INT NOT NULL,
    [ORDER_NO] DECIMAL (10) NOT NULL,
    [USERNAME] VARCHAR (20) NOT NULL,
    PRIMARY KEY CLUSTERED ([ORDER_NO] ASC, [STAFF_ID] ASC),
    CONSTRAINT [FK_DELIVERY_ToTable_1] FOREIGN KEY ([ORDER_NO]) REFERENCES [dbo].[ORDER_DETAILS] ([ORDER_NO]),
    CONSTRAINT [FK_DELIVERY_ToTable_2] FOREIGN KEY ([USERNAME]) REFERENCES [dbo].[CUSTOMER] ([USERNAME]), 
    CONSTRAINT [FK_DELIVERY_ToTable] FOREIGN KEY ([STAFF_ID]) REFERENCES [STAFF]([STAFF_ID])
);

